{% set version = '0.7-1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rmpfr
  version: {{ version|replace("-", "_") }}

source:
  fn: Rmpfr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/Rmpfr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Rmpfr/Rmpfr_{{ version }}.tar.gz
  sha256: 9b3021617a22b0710b0f1acc279290762317ff123fd9e8fd03f1449f4bbfe204

# There's some sort of issue with the gmp library on Windows
build:
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: MASS, polynom, sfsmisc (>= 1.0-20), Matrix
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-gmp >=0.5_8
    - mpfr

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-gmp >=0.5_8
    - mpfr

test:
  commands:
    - $R -e "library('Rmpfr')"           # [not win]
    - "\"%R%\" -e \"library('Rmpfr')\""  # [win]

about:
  home: http://rmpfr.r-forge.r-project.org/
  license: GPL (>= 2)
  summary: Arithmetic (via S4 classes and methods) for arbitrary precision floating point numbers,
    including transcendental ("special") functions.  To this end, the package interfaces
    to the 'LGPL' licensed 'MPFR' (Multiple Precision Floating-Point Reliable) Library
    which itself is based on the 'GMP' (GNU Multiple Precision) Library.
  license_family: GPL3
extra:
  recipe-maintainers:
    - dpryan79
    - cbrueffer
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
