# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_c_compilerclangtarget_platformosx-64
    - CONFIG=osx_c_compilertoolchain_ctarget_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "qV12y8LnHbumYb7FsG2ua0aVUQV+t2LWFmgxpC3x4WJhMDdRufM8GuaLO7jHm5CR9pDyvLNlFPiqu6Rw/2ANFJ1+IcI5ru/KilysDA6QRvuqzDgK4uYBol6DuGdTpj3wSE5eE7tflj/3VhZgZk8wod+5Af1htA8kzjX9IW/K8hwgWqa9mWh4G7+MRWDdINHf43Czg9knnqMk+gQTA1K68EMwjYXPNjwqtCXnI/BOoHMQv+7c60l9Yo/qi9Iqo2M9VdRlbVOkSdXLcOo3LIhcgnfivsjT1oStv7yidYalyM+nNodkgBhDM4/Kg+Miu/0yby0UBZ6kh+22QDxhGPDkbVHtiEOJ/Yl/tVZH1yLm06c0WIRzhStOskLAEoSJIBKf7BblXevALxQ/FTmJO00I2+Cc4ktc210usd+rl9sVIBB/Iboi5MiPRLD40Hx1G7LZDLHR+KZPqFElEhG5/zuvRcbJz4nMB6hDdi5a2aH1Ti/t4nUnBDoALlMwsBB0RE2BWyGKOlpLb5yWziLUrdq2nIp20QTODEqYB5Pzl0wrM9Hab7NYrDAos/NUNAZO8zt7Y+X1lY5V4Ph7KThWAjPNfnBMJx9m76mUUcJPaL+D5Xm15ldFCJnhH45vP0TXVCXDaJzKDr5xdLsdhju/RQLMbEAPvfyiZqJ0WrqaS8VlHI8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml